MOCK_EVENTS: list[dict] = [
    {
        "id": "mock-alert-airflow-daily-orders",
        "kind": "alert",
        "timestamp": "2026-05-09T12:00:00+00:00",
        "severity": "critical",
        "title": "daily_orders_refresh failed in Airflow",
        "detail": "DAG run failed after retry exhaustion.",
        "state": "needs_approval",
        "requires_approval": True,
        "acknowledged_at": None,
        "acknowledged_by": None,
        "resolved_at": None,
        "resolved_by": None,
        "connector_slug": "airflow",
        "logo_key": "apache-airflow",
        "actions": ["approve", "acknowledge", "resolve"],
    },
    {
        "id": "mock-alert-schema-drift-orders",
        "kind": "alert",
        "timestamp": "2026-05-09T11:45:00+00:00",
        "severity": "warning",
        "title": "Schema drift in core.orders - column status type changed",
        "detail": "Column status changed from varchar(32) to varchar(255).",
        "state": "open",
        "requires_approval": False,
        "acknowledged_at": None,
        "acknowledged_by": None,
        "resolved_at": None,
        "resolved_by": None,
        "connector_slug": "postgres",
        "logo_key": "postgresql",
        "actions": ["acknowledge", "resolve"],
    },
    {
        "id": "mock-alert-slow-query-weekly-customer-360",
        "kind": "alert",
        "timestamp": "2026-05-09T11:20:00+00:00",
        "severity": "info",
        "title": "Slow query detected - `weekly_customer_360.sql`",
        "detail": "Query duration exceeded the configured threshold.",
        "state": "acknowledged",
        "requires_approval": False,
        "acknowledged_at": "2026-05-09T11:24:00+00:00",
        "acknowledged_by": "admin@dataclaw.local",
        "resolved_at": None,
        "resolved_by": None,
        "connector_slug": "postgres",
        "logo_key": "postgresql",
        "actions": ["acknowledge", "resolve"],
    },
    {
        "id": "mock-alert-dbt-not-null-orders-customer-id",
        "kind": "alert",
        "timestamp": "2026-05-09T10:55:00+00:00",
        "severity": "warning",
        "title": "dbt test `not_null_orders_customer_id` failed",
        "detail": "The not_null test failed for 18 rows.",
        "state": "resolved",
        "requires_approval": False,
        "acknowledged_at": "2026-05-09T10:57:00+00:00",
        "acknowledged_by": "admin@dataclaw.local",
        "resolved_at": "2026-05-09T11:05:00+00:00",
        "resolved_by": "admin@dataclaw.local",
        "connector_slug": "dbt",
        "logo_key": "dbt",
        "actions": [],
    },
    {
        "id": "mock-run-freshness-agent",
        "kind": "agent_run",
        "timestamp": "2026-05-09T10:30:00+00:00",
        "severity": "info",
        "title": "freshness_agent - completed",
        "detail": "freshness_agent: 47 tables checked",
        "state": "completed",
        "agent_name": "freshness_agent",
        "agent_icon_key": "activity",
        "requires_approval": False,
        "timeline": [{"step": "freshness_scan", "status": "completed", "detail": "47 tables checked."}],
        "actions": [],
    },
    {
        "id": "mock-run-docs-agent",
        "kind": "agent_run",
        "timestamp": "2026-05-09T10:00:00+00:00",
        "severity": "critical",
        "title": "docs_agent - failed",
        "detail": "docs_agent: timeout after 600s",
        "state": "failed",
        "agent_name": "docs_agent",
        "agent_icon_key": "file-text",
        "requires_approval": False,
        "timeline": [{"step": "column_description_generation", "status": "failed", "detail": "timeout after 600s"}],
        "actions": [],
    },
]
