#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from app.services.connectors.catalog import CATALOG_BY_SLUG, Stability  # noqa: E402
from app.services.mcp_catalog import tools_for_slug  # noqa: E402


TIER_LABELS = {
    Stability.STABLE: "🟢 Stable",
    Stability.STABLE_READ_ONLY: "🔵 Stable (read-only)",
    Stability.BETA: "🟡 Beta",
    Stability.KNOWN_ISSUE: "🔴 Known issue",
    Stability.UNSUPPORTED: "🚫 Unsupported",
}

TIER_MEANINGS = {
    Stability.STABLE: "Read + write exercised live; audit/approval flow verified. Use in production.",
    Stability.STABLE_READ_ONLY: "Reads production-ready. Writes pending adapter work or intentionally not executed.",
    Stability.BETA: "Usable, but fixture-backed or live E2E coverage is incomplete. Not recommended for production write workflows.",
    Stability.KNOWN_ISSUE: "Adapter has a documented bug that prevents normal use. Hidden by default unless explicitly enabled.",
    Stability.UNSUPPORTED: "Adapter retained for compatibility only; service or auth flow is not usable for new production installs.",
}

CATEGORY_ORDER = {
    "data_store": 0,
    "knowledge_base": 1,
    "etl_orchestration": 2,
    "llm": 3,
    "llm_provider": 3,
}

CATEGORY_LABELS = {
    "data_store": "Data store",
    "knowledge_base": "Knowledge base",
    "etl_orchestration": "ETL/orchestration",
    "llm": "LLM",
    "llm_provider": "LLM provider",
}

VERIFICATION_LABELS = {
    "credential_required": "Credential required",
    "demo": "Demo",
    "not_configured": "Not configured",
    "real": "Real",
}


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _count_status(value: int) -> str:
    return f"✅ {value}" if value else "-"


def _label(value: object, labels: dict[str, str]) -> str:
    raw = str(value)
    return labels.get(raw, raw.replace("_", " ").title())


def render_connector_matrix() -> str:
    connectors = sorted(
        CATALOG_BY_SLUG.values(),
        key=lambda item: (CATEGORY_ORDER.get(str(item.category), 99), item.slug),
    )
    lines = [
        "# Connector Matrix",
        "",
        "<!-- Generated by scripts/generate_connector_matrix.py. Do not hand-edit connector rows. -->",
        "",
        (
            f"DataClaw ships with {len(connectors)} catalog entries. This page is generated from "
            "`backend/app/services/connectors/catalog.py` and MCP tool coverage from "
            "`backend/app/services/mcp_catalog.py`."
        ),
        "",
        "See [Stability Tiers](./stability-tiers.md) for the policy behind each tier.",
        "",
        "## Stability Tiers",
        "",
        "| Tier | Meaning |",
        "|------|---------|",
    ]
    for tier in Stability:
        lines.append(f"| {TIER_LABELS[tier]} | {TIER_MEANINGS[tier]} |")

    lines.extend(
        [
            "",
            "## Per-Connector Status",
            "",
            "| Connector | Category | Tier | Verification | Read tools | Write tools | Known issues | Stability evidence |",
            "|-----------|----------|------|--------------|------------|-------------|--------------|--------------------|",
        ]
    )
    for item in connectors:
        read_tools, write_tools = tools_for_slug(item.slug)
        known_issues = "<br>".join(_escape(issue) for issue in item.known_issues) or "-"
        evidence = _escape(item.stability_notes or "-")
        lines.append(
            "| "
            f"`{item.slug}` | "
            f"{_escape(_label(item.category, CATEGORY_LABELS))} | "
            f"{TIER_LABELS[item.stability]} | "
            f"{_escape(_label(item.local_verification, VERIFICATION_LABELS))} | "
            f"{_count_status(len(read_tools))} | "
            f"{_count_status(len(write_tools))} | "
            f"{known_issues} | "
            f"{evidence} |"
        )

    lines.extend(
        [
            "",
            "## Release Gate Evidence",
            "",
            "Connector tier changes are code changes first. Promote a connector only when the release evidence backs the tier:",
            "",
            "- `stable`: live read/write path exercised, approval gate observed for destructive writes, and `AgentWriteAudit` verified.",
            "- `stable_read_only`: live read path exercised; write tools either absent, intentionally blocked, or documented as pending.",
            "- `beta`: adapter is wired and tested with fixtures or partial live coverage, but production evidence is incomplete.",
            "- `known_issue`: adapter routes exist, but a code-level or vendor-level issue blocks normal use.",
            "- `unsupported`: retained for compatibility only.",
            "",
            "The default CI gate must include this generated-doc parity check plus core stable connector tests. Full connector "
            "evidence is produced by `make test-integration-full` and the `integration-full` workflow.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    target = ROOT / "docs" / "CONNECTOR_MATRIX.md"
    target.write_text(render_connector_matrix(), encoding="utf-8")
    print(f"Wrote {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
