import {
  Activity,
  AlarmClock,
  Archive,
  BarChart3,
  Bot,
  Brain,
  ChartSpline,
  CircleGauge,
  ClipboardCheck,
  Code2,
  Database,
  FileSearch,
  FileText,
  GitBranch,
  GitPullRequest,
  KeyRound,
  LineChart,
  LockKeyhole,
  Network,
  Radar,
  SearchCheck,
  ShieldCheck,
  Sparkles,
  Table2,
  TerminalSquare,
  Wand2,
  Workflow,
} from "lucide-react";

export const AGENT_ICONS = {
  activity: Activity,
  alarm: AlarmClock,
  archive: Archive,
  "bar-chart": BarChart3,
  bot: Bot,
  brain: Brain,
  "chart-spline": ChartSpline,
  gauge: CircleGauge,
  checklist: ClipboardCheck,
  code: Code2,
  database: Database,
  "file-search": FileSearch,
  "file-text": FileText,
  "git-branch": GitBranch,
  "git-pr": GitPullRequest,
  key: KeyRound,
  "line-chart": LineChart,
  lock: LockKeyhole,
  network: Network,
  radar: Radar,
  "search-check": SearchCheck,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  table: Table2,
  terminal: TerminalSquare,
  wand: Wand2,
  workflow: Workflow,
};

export type AgentIconKey = keyof typeof AGENT_ICONS;
